import React from "react";

export default function schedule(props) {
  return (
    <div className="space">
      <div className="shcedule search-space-table">
        <table className="table table-hover table-light table-striped">
          <thead>
            <tr>
              <td></td>
              <td>Lundi</td>
              <td>Mardi</td>
              <td>Mercredi</td>
              <td>Jeudi</td>
              <td>Vendredi</td>
              <td>Samedi</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>10:30</td>
            </tr>
            <tr>
              <td>11:00</td>
            </tr>
            <tr>
              <td>11:30</td>
            </tr>
            <tr>
              <td>12:00</td>
            </tr>
            <tr>
              <td>12:30</td>
            </tr>
            <tr>
              <td>13:00</td>
            </tr>
            <tr>
              <td>13:30</td>
            </tr>
            <tr>
              <td>14:00</td>
            </tr>
            <tr>
              <td>14:30</td>
            </tr>
            <tr>
              <td>15:00</td>
            </tr>
            <tr>
              <td>15:30</td>
            </tr>
            <tr>
              <td>16:00</td>
            </tr>
            <tr>
              <td>16:30</td>
            </tr>
            <tr>
              <td>17:00</td>
            </tr>
            <tr>
              <td>17:30</td>
            </tr>
            <tr>
              <td>18:00</td>
            </tr>
            <tr>
              <td>18:30</td>
            </tr>
            <tr>
              <td>19:00</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
